# Site settings
title: My blog
header-img: img/home-bg.png
email: a_papacostas@yahoo.com
copyright_name: ms94ap
description: > # this means to ignore newlines until "baseurl:"
   
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ms94ap
learn_profile: ms94ap
email_username: a_papacostas@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
